name: "Code Quality Check"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/code_quality.yml"

jobs:
  phpcs:
    name: "PHP CodeSniffer"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v4
      - name: Run PHPCS
        uses: chekalsky/phpcs-action@v1
  phpmd:
    name: "PHP MessDetector"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v4
      - name: Run PHPMD
        uses: GeneaLabs/action-reviewdog-phpmd@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: 'warning'
          reporter: github-pr-check
          standard: './phpmd.xml'
          target_directory: 'src'
